exchange-rate-api:
  base-url: https://v6.exchangerate-api.com/
  api-key: 0aa7dae4a33e84e66a32fff1
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect